
CREATE SEQUENCE IF NOT EXISTS Toad_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE Toad
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    age         INTEGER,
    name        VARCHAR(255)                            NOT NULL,
    weight      INTEGER,
    gender      CHAR,
    description VARCHAR(1000),
    birthday    date,
    CONSTRAINT pk_toad PRIMARY KEY (id)
);

ALTER TABLE Toad
    ADD CONSTRAINT uc_0e52d386d35dfac7a24e5749f UNIQUE (name, age);