
CREATE SEQUENCE IF NOT EXISTS Toad_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE Toad
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    warts       INTEGER,
    name        VARCHAR(50)                            NOT NULL,
    weight      INTEGER,
    gender      CHAR,
    description VARCHAR(100),
    birthday    date,
    CONSTRAINT pk_toad PRIMARY KEY (id),
    CONSTRAINT uc_30fcbf7c5de425cd429b1955c UNIQUE (name, birthday),
    CONSTRAINT uc_0e52d386d35dfac7a24e5749f UNIQUE (name, warts)
);

